[package]
name = "luau_app"
version = "0.1.0"
edition = "2021"

[dependencies]
mlua = { version = "0.9.8", features = ["luau"] }
luneweb = { path = "../../LuneWeb-rs/" }
tokio = { version = "1.37.0", features = ["macros"] }
include_dir = "0.7.3"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["wincon", "winuser"] }
